CHANGELOG.md, src/android/com/outsystems/plugins/healthfitness/store/HealthStore.kt
Fixes a small bug we had on the requestPermissions for Android. We were not using the custom permissions in the request for GoogleSignIn.
Also added a verification so that we only ask for GoogleSignIn permissions when necessary.
https://outsystemsrd.atlassian.net/browse/RMET-971
Tested locally with Android 11 device. Also tested MABS 7.1 build and everything is working fine.
=> RMET-971 Health and Fitness Plugin - Fix android request permissions

CHANGELOG.md, src/android/com/outsystems/plugins/healthfitness/HealthFitnessError.kt, src/android/com/outsystems/plugins/healthfitness/OSHealthFitness.kt, src/android/com/outsystems/plugins/healthfitness/store/GoogleFitVariable.kt, src/android/com/outsystems/plugins/healthfitness/store/HealthStore.kt, www/OSHealthFitness.js
Adds implementation for WriteProfileData method in Android. As of now, all the profile variables we use can be passed as Float, so we use the DataPoint.builder.setField method for Float values (useful for Height and Weight).
https://outsystemsrd.atlassian.net/browse/RMET-976
Tested locally in an Android 11 device. Was able to Write data for all the 4 profile variables. MABS 7.1 build also working.
=> RMET-976 Health & Fitness Plugin - WriteProfileData android

CHANGELOG.md, src/android/com/outsystems/plugins/healthfitness/store/HealthStore.kt
Adds getLastSIgnInAccount to get account for reading and writing data.
References: https://outsystemsrd.atlassian.net/browse/RMET-1022
Tested locally in an Android 11 device. Was able to get the last record for all 3 types of data. MABS 7.1 build also working.
=> RMET-1022 Health & Fitness Plugin - Get Google account the right way

CHANGELOG.md, src/android/com/outsystems/plugins/healthfitness/AndroidPlatformInterface.kt, src/android/com/outsystems/plugins/healthfitness/CordovaImplementation.kt, src/android/com/outsystems/plugins/healthfitness/HealthFitnessError.kt, src/android/com/outsystems/plugins/healthfitness/OSHealthFitness.kt, src/android/com/outsystems/plugins/healthfitness/store/HealthStore.kt
Fixes requestPermissions callback to be handled by onActivityResult.
Also changes value received by writeData to be a float instead of a String.
References: https://outsystemsrd.atlassian.net/browse/RMET-996
Tested locally in an Android 11 device. Tested case when we cancel the permissions, and the case where we accept the permissions. MABS 7.1 build also working.
=> RMET-996 Health & Fitness Plugin - Fix android permissions callback

src/android/com/outsystems/plugins/healthfitness/AndroidPlatformInterface.kt, src/android/com/outsystems/plugins/healthfitness/CordovaImplementation.kt, src/android/com/outsystems/plugins/healthfitness/MyDataUpdateService.kt, src/android/com/outsystems/plugins/healthfitness/OSHealthFitness.kt, src/android/com/outsystems/plugins/healthfitness/store/AdvancedQuery.kt, src/android/com/outsystems/plugins/healthfitness/store/AdvancedQueryResponseBlock.kt, src/android/com/outsystems/plugins/healthfitness/store/HealthStore.kt
Removed references to Kotlin Instant. Using Calendar instead.
ACTIVITY_RECOGNITION is only requested on Android 10 or higher.
Also took the opportunity to optimize imports.
Android code continuously made use of "RequiresApi" annotation. The reason behind this was that the code used a few features to convert date, time and milliseconds. This was not the optimal, since MABS supports older versions than Android 8.
Furthermore, Manifest.permission.ACTIVITY_RECOGNITION is only available on Android 10 or higher. This was cause the app to never ask for GooglePermissions because this Android Permissions was never granted on lower version devices.
Tested on Device Android 11, and Emulator Android 9.
- [] Pull request title follows the format `RNMT-XXXX <title>`
- [] CHANGELOG.md file is correctly …
=> Android 8 requirement remove

src/android/com/outsystems/plugins/healthfitness/OSHealthFitness.kt
A small fix on InitPermissions.
We changed the way our HealthStore uses the android interface. In this case we are no longer using this interface directly. Now, if there's an error, an exception is thrown and we are able to abstract the interface from the HealthStore.
Tested on device
=> Fixed bug in request permissions

CHANGELOG.md, src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/background/BackgroundJobParameters.kt, src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/background/VariableUpdateService.kt, src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/background/database/AppDatabase.kt, src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/background/database/BackgroundJob.kt, src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/background/database/BackgroundJobDao.kt, src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/background/database/DatabaseManager.kt, src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/background/database/DatabaseManagerInterface.kt, src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/background/database/Notification.kt, src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/background/database/NotificationDao.kt, src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/store/HealthStore.kt
- This PR adds the implementation of the NotificationFrequency, also known as waiting period, on Android.
- For NotificationFrequency equal to SECOND or MINUTE, we always wait for the next full SECOND / MINUTE to pass before sending another notification. For the rest of them, like HOUR and DAY, we only wait for the beginning of the next time unit. For example, if we send a notification at 4:55PM and at 5:00PM we have a new notification to be sent, we will send it, because we are in a new hour. On the other hand, if the frequency is MINUTE and we send a notification at 4:55PM and 30 seconds, we will wait until 4:56PM and 30 seconds to send a new notification.
- This PR also includes the work done by @nflsilva regarding the Migration of the Room database, since we added some new values to …
=> RMET-1240 H&F Plugin - Implement Notification Frequency (waiting period) on Android

src/android/com/outsystems/plugins/healthfitness/OSHealthFitness.kt, src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/HealthFitnessError.kt, src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/background/VariableUpdateService.kt, src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/background/database/AppDatabase.kt, src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/background/database/BackgroundJob.kt, src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/background/database/BackgroundJobDao.kt, src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/background/database/DatabaseManager.kt, src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/background/database/DatabaseManagerInterface.kt, src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/store/HealthFitnessManager.kt, src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/store/HealthFitnessManagerInterface.kt, src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/store/HealthStore.kt, www/OSHealthFitness.js
This PR implements the delete background job functionality Android
https://outsystemsrd.atlassian.net/browse/RMET-1232
Tested on a real device with the Updated Demo app
=> RMET-1203 Delete background job Android implementation

src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/store/HealthStore.kt
- Adds a small fix to reset the nextNotificationTimestamp to 0 when the notificationFrequency or the notificationFrequencyGrouping change.
References: https://outsystemsrd.atlassian.net/browse/RMET-1235
Tested locally in Android 11. MABS 7.2 and 8.0
=> RMET-1235 H&F Plugin - Reset nextNotificationTimestamp in update

CHANGELOG.md, plugin.xml
- This PR fixes a bug found that when clicking a notification from the notification panel, the app would not open. Fixed the package name of the ClickActivity.
References: https://outsystemsrd.atlassian.net/browse/RMET-1268
MABS builds working. Tested with MABS build and clicking the notification opens the app.
=> RMET-1268 H&F Plugin - Fixing package name for ClickActivity class

tests/android/HealthFitnessTests/app/build.gradle, tests/android/HealthFitnessTests/app/src/test/java/com/outsystems/plugins/healthfitness/mock/AndroidPlatformMock.kt, tests/android/HealthFitnessTests/build.gradle
So we can get test coverage reports, this PR adds JaCoCo to estimate the unit test coverage and Sonarqube to centralise those reports
Also removing an annotation from AndroidPlatformMock. From what I've seen it's not needed and it was breaking the unit tests as the JUnit runner broken when running a class without tests
=> Adds JaCoCo and Sonarqube support

CHANGELOG.md, src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/background/VariableUpdateService.kt, src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/store/HealthFitnessManager.kt
- MABS 7 builds for an app with the plugin were breaking. 
- For the MABS 7 builds, we cannot use PendingIntent.FLAG_MUTABLE, since this was only introduced in API Level 31. Instead, we need to use the corresponding literal value which is 33554432
References: https://outsystemsrd.atlassian.net/browse/RMET-1460
Built on MABS 7 and MABS 8. Tested plugin, receiving notifications for STEPS and WEIGHT.
=> RMET-1460 H&F Plugin - Fix to use constant literal value because of MABS 7

CHANGELOG.md, package.json, plugin.xml
Added to the info.plist file a property to identify the background tasks used in the plugin.
The property added is: BGTaskSchedulerPermittedIdentifiers.
Manually tests executed
=> RMET-1689 ::: Fix - App Store submission background identifier requeired 

CHANGELOG.md, plugin.xml, src/android/build.gradle, src/android/com/outsystems/plugins/healthfitness/OSHealthFitness.kt
Since Android 13 now requires permission just like iOS we are want the same feature on Android.
The prompt to the user will be at the same moment that iOS, when the user creates the first background job.
Adds the `BODY_SENSORS_BACKGROUND ` to the Manifest.xml. Also a change required by Android 13.
Closes issues: https://outsystemsrd.atlassian.net/browse/RMET-1684,
https://outsystemsrd.atlassian.net/browse/RMET-1685
To create the request permission we implemented in a base level, updating OSCore-Android, OSCordova-Android and created a new Library called OSNotificationPermissionsLib-Android.
=> RMET-1684 ::: Request Notification Permissions - Android 13 update

CHANGELOG.md, src/android/com/outsystems/plugins/healthfitness/OSHealthFitness.kt
- Build error happening in an app with both the Health & Fitness and the FB Cloud Messaging plugin. Changing the call to a safe call fixes the build error.
References: https://outsystemsrd.atlassian.net/browse/RMET-2041
This closes and RPM.
Tested with MABS 8.1 build.
=> RMET-2041 - Health & Fitness Plugin - Add safe call to avoid build error

CHANGELOG.md, src/android/build.gradle
- Replaced the deprecated `jcenter` repository by a more updated `mavenCentral`
https://outsystemsrd.atlassian.net/browse/RMET-2036
Tested on MABS 8 and MABS 9 builds, on Android 12 device.
=> RMET-2036 :: Replaced jcenter by mavenCentral

CHANGELOG.md, src/android/build.gradle, src/android/com/outsystems/plugins/healthfitness/OSHealthFitness.kt
- This PR re-implements the `RequestPermissions` feature - `initAndRequestPermissions` method in the Cordova bridge.
- It also updates the version of the `OSHealthFitnessLib-Android` library
We're migrating the H&F library from the Google Fit Android API to the Health Connect SDK.
References: https://outsystemsrd.atlassian.net/browse/RMET-3046
- Unit tests for the `RequestPermissions` feature were added to `src/test/kotlin/com/outsystems/plugins/healthfitness/RequestPermissionsTest.kt`.
- MABS 9 build: https://intranet.outsystems.net/MABS/BuildDetail.aspx?BuildId=94bf797e81f8658511d4c27a556a8bd06ae16352
- MABS 10 build: https://intranet.outsystems.net/MABS/BuildDetail.aspx?BuildId=017c0cbd5c4c3fc5ab855f4b01b19bd909b904d8
- Tested in Android 14 and Android 13.
=> RMET-3046 H&F Cordova Plugin - Migrate RequestPermissions to HealthConnect

CHANGELOG.md, src/android/build.gradle, src/android/com/outsystems/plugins/healthfitness/OSHealthFitness.kt
- This PR re-implements the `GetLastRecord` feature, which deals with:
- `GetProfileData`
- `GetHealthData`
- `GetFitnessData`
- It also includes a refactor on the `writeData` method of the Cordova bridge, where we remove a validation that is already done on the Android library, and so there's no need to do it here.
References:
- https://outsystemsrd.atlassian.net/browse/RMET-3048
- https://outsystemsrd.atlassian.net/browse/RMET-3065
- https://outsystemsrd.atlassian.net/browse/RMET-3066
- Tested in Android 14 Pixel 7 and Android 13 Samsung S20 FE.
- Calling the `GetHealthData` client action for the `BLOOD_PRESSURE` variable:
=> RMET-3048 :: Migrate GetLastRecord to HealthConnect

CHANGELOG.md, src/android/com/outsystems/plugins/healthfitness/OSHealthFitness.kt
-  This PR re-implements the Advance Query feature.
https://outsystemsrd.atlassian.net/browse/RMET-3047
- Tested in Android 14 Pixel 7.
=> RMET-3047 Android Advance Query

CHANGELOG.md, src/android/build.gradle, src/android/com/outsystems/plugins/healthfitness/OSHealthFitness.kt
- Change `deleteBackgroundJob` to use the new `HealthConnectViewModel` version.
https://outsystemsrd.atlassian.net/browse/RMET-3068
=> RMET-3068 ::: Android ::: Migrate Delete Background Jobs 

CHANGELOG.md, hooks/androidCopyPreferencesPermissions.js, package.json, plugin.xml, src/android/build.gradle
- Implements `androidCopyPreferencesPermissions.js` hook that does the following:
- Adds the health connect permissions (e.g. `android.permission.health.READ_HEART_RATE`) to both the `AndroidManfiest.xml` file and the `health_permissions.xml` file.
- Adds the background job permissions (e.g. `android.permission.POST_NOTIFICATIONS`) to the `AndroidManifest.xml` file.
- Copies the notification title and content for the foreground notification to be shown when the app is processing a background job.
- It also adds the `PermissionsRationaleActivity` to the `AndroidManifest.xml` file, tying the `health_permissions.xml` file to it.
References: https://outsystemsrd.atlassian.net/browse/RMET-3142
MABS 10 build: https://intranet.outsystems.net/MABS/BuildDetail.aspx?BuildId=8a73f6d9ea8fd632c0adba280 …
=> RMET- 3142 H&F Plugin - Hook for permissions

CHANGELOG.md, src/android/com/outsystems/plugins/healthfitness/OSHealthFitness.kt, www/OSHealthFitness.js
- This PR adds the `disableHealthConnect` feature
- This PR also deprecates the `disableGoogleFit` feature
https://outsystemsrd.atlassian.net/browse/RMET-3070
Tested in Android 14 on Pixel 8 Pro.
=> RMET-3070 H&F Plugin - Implement disableHealthConnect feature and Deprecate disableGoogleFit

CHANGELOG.md, hooks/androidCopyPreferencesPermissions.js, src/android/build.gradle, src/android/com/outsystems/plugins/healthfitness/OSHealthFitness.kt
- This PR adds the code to request the `SCHEDULE_EXACT_ALARM` permission that is necessary when working with exact alarms, for Android >= 14.
- It also adds this permission to the app's manifest, adding it in `hooks/androidCopyPreferencesPermissions.js`.
- It also updates the dependency to the` OSHealthFitnessLib-Android` library, also applying some minor updates to the calls to `setBackgroundJob`, `deleteBackgroundJob`, and `advancedQuery`.
References: https://outsystemsrd.atlassian.net/browse/RMET-3190
- All unit tests passing.
- MABS 10 build: https://intranet.outsystems.net/MABS/BuildDetail.aspx?BuildId=a4d36f7296e71b7cf49c9d289f379072999eb8d9
- Tested in Android 14 (Pixel 7), Android 13 (Samsung A51), and Android 12 (Pixel 3XL)
=> RMET-3190 H&F Plugin - Use exact alarms for background jobs

CHANGELOG.md, hooks/androidCopyPrivacyUrlEnv.js, src/android/build.gradle
- This PR adds an alternative way of checking if the privacy policy file exists.
- Because in ODC, resources have their original name changed with a suffix appended, we need to check for files which names contain the original file name (`HealthConnect_PrivacyPolicy`).
References: https://outsystemsrd.atlassian.net/browse/RMET-3246
Tested with ODC MABS 10 build: https://intranet.outsystems.net/MABS/BuildDetail.aspx?BuildId=a48cd6a91fe3ad31a589be442e7b3b7be2b9db46
=> RMET-3246 H&F Plugin - Fix hook for ODC

www/OSHealthFitness.js
- Removes the `summaryVariables` parameter from `requestPermissions` in `OSHealthFitness.js`
- Removes the `disconnectFromGoogleFit` function from `OSHealthFitness.js`
We don't use summary variables, so we might as well remove the parameter. Also, the new plugin version no longer offers the `disconnectFromGoogleFit` feature, as it was replaced by `disconnectFromHealthConnect`.
References: https://outsystemsrd.atlassian.net/browse/RMET-3134
Tested RequestPermissions feature in Android 14 to make sure that it works properly without passing summary variables, and it does.
=> RMET-3134 H&F Plugin - Remove unused function and parameter

CHANGELOG.md, plugin.xml
- Removes the `PermissionsRationaleActivity` from the `plugin.xml`.
- This was breaking the feature of opening the privacy policy page for Android <= 13.
- The library already adds this, so the plugin doesn't need to.
Tested on Android 14 (Pixel 7), Android 13 (Samsung A51), Android 12 (Pixel 3XL)
MABS 10 build: https://intranet.outsystems.net/MABS/BuildDetail.aspx?BuildId=79a1545de83459f2d94954e590e8e958fd7b2849
=> RMET-3134 H&F Plugin - Fix privacy policy opening for Android <= 13

CHANGELOG.md, hooks/androidCopyPreferencesPermissions.js
- This PR adds support for the `OxygenSaturation` variable by adding the read and write permissions to the android hooks.
References: https://outsystemsrd.atlassian.net/browse/RMET-3363
https://outsystemsrd.atlassian.net/wiki/spaces/RDME/pages/4081516683/LLD+-+Adding+support+for+Oxygen+Saturation
- Tested in Android 14.
=> RMET-3363 - Add OxygenSaturation Permissions

CHANGELOG.md, hooks/androidCopyPrivacyUrlEnv.js
- Include the file extension on the `policyFileExists` method. Since ODC adds some text between the file name and extension, add some log to validate that the file starts with the file name and ends with the 'txt' format.
- Remove some redundant code.
https://outsystemsrd.atlassian.net/browse/RMET-3406
Manual testing was done to validate the fix.
=> RMET-3406 ::: Android ::: Add More Verifications for Privacy Policy File

CHANGELOG.md, hooks/androidCopyPreferencesPermissions.js, package.json, plugin.xml, src/android/build.gradle
It includes an update to the `xmldom` dependency, fixing an Snyk vulnerability found with version `0.6.0`.
=> Prepare Release of `2.2.0`

CHANGELOG.md, package.json, plugin.xml, src/android/build.gradle, src/android/com/outsystems/plugins/healthfitness/OSHealthFitness.kt, src/android/com/outsystems/plugins/healthfitness/OSHealthFitnessWarning.kt, src/android/com/outsystems/plugins/healthfitness/TimeUnitSerializer.kt
This PR:
- updates the library's version to include the changes made to advance query
- changes the plugin bridge to extend `CordovaPlugin` instead of CordovaImplementation
- removes the logic related with MILLISECONDS and SECONDS to the bridge: the library was already converting them into 1 minute intervals, only because of backwards compatibility with the OutSystems wrapper. As such, the Android library sends a warning stating this data manipulation and once iOS is updated, this can be removed to only the OS Wrapper
https://outsystemsrd.atlassian.net/browse/RMET-3831
=> RMET-3831 :: Revamp + Fix of Advanced Query logic

CHANGELOG.md, hooks/androidCopyPreferencesPermissions.js, hooks/androidCopyPrivacyUrlEnv.js
- Updates hook to avoid duplicates in `strings.xml` and `AndroidManifest.xml`
- If the hook runs more than once in a build for some reason, the values it adds would be duplicated, which would cause the Android build to fail if values were duplicated in `strings.xml`. If permissions are duplicated in the AndroidManifest.xml file, the build wouldn't fail, but we should still avoid duplicating them.
- This happens when building apps with MOCA instead of MABS
References: https://outsystemsrd.atlassian.net/browse/RMET-4025
Tested MABS 11.1 builds with MOCA instead of MABS.
=> RMET-4025 - Update hook to avoid duplicates in XML files
