CHANGELOG.md
src/android/com/outsystems/plugins/healthfitness/HealthFitnessError.kt
src/android/com/outsystems/plugins/healthfitness/OSHealthFitness.kt
src/android/com/outsystems/plugins/healthfitness/store/HealthStore.kt
www/OSHealthFitness.js

Adds implementation for getLastRecord method in Android. This method will be used by GetFitnessData, GetProfileData and GetHealthData client actions in the OS wrapper.
**Important**
Right now we are using the current date as the `endDate` and the current date - 1 month as the `startDate`. We should discuss if we want a bigger period to get the last record. For example, there may be no HeartRate records for the last month (30 days).
https://outsystemsrd.atlassian.net/browse/RMET-831
Tested locally in an Android 11 device. Was able to get the last record for all 3 types of data. MABS 7.1 build also working.

RMET-831 Health & Fitness Plugin - Android simple query

---

src/ios/AuthorizationErrors.swift
src/ios/HealthFitnessPlugin.swift
src/ios/HealthKitManager.swift
src/ios/OSHealthFitness.swift

Verify Permissions for variable parameter on advancedQuery and writeData methods.
Also changes value received by writeData to be a float instead of a String.
References: https://outsystemsrd.atlassian.net/browse/RMET-996

RMET-1023 Health & Fitness Plugin - Feat: Verify Permissions on iOS

---

plugin.xml
src/android/com/outsystems/plugins/healthfitness/HealthFitnessError.kt
src/android/com/outsystems/plugins/healthfitness/OSHealthFitness.kt
src/android/com/outsystems/plugins/healthfitness/store/AdvancedQuery.kt
src/android/com/outsystems/plugins/healthfitness/store/AdvancedQueryParameters.kt
src/android/com/outsystems/plugins/healthfitness/store/GoogleFitVariable.kt
src/android/com/outsystems/plugins/healthfitness/store/HealthStore.kt

Verify Permissions for variable parameter on advancedQuery and writeData methods.
Verify allowed operations for each variable.
Also, code refactoring on Permissions.
Also, major code refactoring on AdvancedQuery.
Removed old background service code.
References: https://outsystemsrd.atlassian.net/browse/RMET-1023

RMET-1023 Health & Fitness Plugin - Feat: Verify variables and permissions

---

src/ios/HealthKitManager.swift
src/ios/HealthKitTypes.swift

Fixes a bug related with the operations allowed and added new type to map of all variables

A few bug fixes in iOS

---

src/android/com/outsystems/plugins/healthfitness/store/HealthStore.kt

Add field type to BASAL_METABOLIC_RATE variable
Also added sendPluginResult to deal with scenario when the value provided is out of range (ex: Height with value in cm - 170 instead of meters - 1.70)
Tested locally in an Android 11 device.

fix: add field type to BASAL_METABOLIC_RATE variable

---

src/ios/AuthorizationErrors.swift
src/ios/HealthKitManager.swift
src/ios/HealthKitTypes.swift
src/ios/OSHealthFitness.swift

Fixes a bug to identify if a wrong data type is passed.
Added raw operation.

Fix: testing data type and operation raw added for iOS

---

src/ios/HealthKitManager.swift
src/ios/HealthKitTypes.swift

Fixes a bug related with the decimal values.

Fix: not necessary cast to float in double values

---

src/ios/AuthorizationErrors.swift
src/ios/HealthKitManager.swift
src/ios/HealthKitTypes.swift
src/ios/OSHealthFitness.swift

Changed error codes and messages to better align with Android.
https://outsystemsrd.atlassian.net/browse/RMET-1066

refactor: Aligned error codes and messages with Android

---

plugin.xml
src/android/com/outsystems/plugins/healthfitness/OSHealthFitness.kt
src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/background/VariableUpdateService.kt
src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/background/database/DatabaseManager.kt
src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/background/database/DatabaseManagerInterface.kt
src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/store/HealthFitnessManager.kt
src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/store/HealthFitnessManagerInterface.kt
src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/store/HealthStore.kt

This code will refactor the code for developing unit tests.
There's a Database interface so it's easy to create a mock for it.
We also removed HealthStore's dependency on android's Context.
Tested on MABS7 and MABS8

RMET-1070 Refactor code for unit tests

---

CHANGELOG.md
plugin.xml
src/android/com/outsystems/plugins/healthfitness/OSHealthFitness.kt
src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/HealthFitnessError.kt
src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/background/BackgroundJobResponseBlock.kt
src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/background/BackgroundJobsResponse.kt
src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/background/database/AppDatabase.kt
src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/background/database/BackgroundJob.kt
src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/background/database/DatabaseManager.kt
src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/background/database/DatabaseManagerInterface.kt
src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/store/HealthStore.kt
www/OSHealthFitness.js

- This PR includes the implementation of the ListBackgroundJobs feature for Android.
References: https://outsystemsrd.atlassian.net/browse/RMET-1239
Tested locally on Android 11 using app generated by MABS in DEV. MABS 7.2 and 8 builds working.

RMET-1239 H&F Plugin - Android ListBackgroundJobs

---

CHANGELOG.md
tests/android/HealthFitnessTests/app/build.gradle
tests/android/HealthFitnessTests/app/src/test/java/com/outsystems/plugins/healthfitness/ListBackgroundJobsTest.kt
tests/android/HealthFitnessTests/app/src/test/java/com/outsystems/plugins/healthfitness/SetBackgroundJobTest.kt
tests/android/HealthFitnessTests/app/src/test/java/com/outsystems/plugins/healthfitness/mock/DatabaseManagerMock.kt
tests/android/HealthFitnessTests/app/src/test/java/com/outsystems/plugins/healthfitness/mock/HealthFitnessManagerMock.kt

- This PR includes the implementation of the Unit Tests for the ListBackgroundJobs feature on Android.
- Also includes some refactoring on the pre-existent unit tests.
References: https://outsystemsrd.atlassian.net/browse/RMET-1239
Ran all the tests locally.

RMET-1239 H&F Plugin - Unit Tests for ListBackgroundJobs in Android

---

CHANGELOG.md
tests/android/HealthFitnessTests/app/src/test/java/com/outsystems/plugins/healthfitness/DeleteBackgroundJobsTest.kt
tests/android/HealthFitnessTests/app/src/test/java/com/outsystems/plugins/healthfitness/ListBackgroundJobsTest.kt
tests/android/HealthFitnessTests/app/src/test/java/com/outsystems/plugins/healthfitness/SetBackgroundJobTest.kt
tests/android/HealthFitnessTests/app/src/test/java/com/outsystems/plugins/healthfitness/mock/DatabaseManagerMock.kt
tests/android/HealthFitnessTests/app/src/test/java/com/outsystems/plugins/healthfitness/mock/HealthFitnessManagerMock.kt

- This PR includes the implementation of the Unit Tests for the DeleteBackgroundJob feature on Android.
- Also includes some refactoring on the pre-existent unit tests.
References: https://outsystemsrd.atlassian.net/browse/RMET-1232
Ran all the tests locally.

RMET-1232 H&F Plugin - Unit Tests DeleteBackgroundJob Android

---

CHANGELOG.md
src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/HealthFitnessError.kt
src/android/com/outsystems/plugins/healthfitness/oshealthfitnesslibrary/store/HealthStore.kt
tests/android/HealthFitnessTests/app/src/test/java/com/outsystems/plugins/healthfitness/DeleteBackgroundJobsTest.kt
tests/android/HealthFitnessTests/app/src/test/java/com/outsystems/plugins/healthfitness/ListBackgroundJobsTest.kt
tests/android/HealthFitnessTests/app/src/test/java/com/outsystems/plugins/healthfitness/SetBackgroundJobTest.kt
tests/android/HealthFitnessTests/app/src/test/java/com/outsystems/plugins/healthfitness/UpdateBackgroundJobsTest.kt
tests/android/HealthFitnessTests/app/src/test/java/com/outsystems/plugins/healthfitness/mock/DatabaseManagerMock.kt
tests/android/HealthFitnessTests/app/src/test/java/com/outsystems/plugins/healthfitness/mock/HealthFitnessManagerMock.kt

- This PR includes the implementation of the Unit Tests for the UpdateBackgroundJob feature on Android.
- Also includes some refactoring on the pre-existent unit tests.
References: https://outsystemsrd.atlassian.net/browse/RMET-1235
Ran all the tests locally.

RMET-1235 H&F - Android Unit Tests UpdateBackgroundJob

---

CHANGELOG.md

Merging development to main in order to release 1.2.1

Release 1.2.1: Dev to main

---

CHANGELOG.md
src/android/build.gradle
src/android/com/outsystems/plugins/healthfitness/OSHealthFitness.kt
www/OSHealthFitness.js

- This PR adds the feature to disconnect from Google Fit.
- It also updates the dependency to OSHealthFitnessLib-Android so that it can use the new feature.
References: https://outsystemsrd.atlassian.net/browse/RMET-2723
- MABS 9 build: https://intranet.outsystems.net/MABS/BuildDetail.aspx?BuildId=c94ffad6a04f28452f93a32d8b0b7857e474f738
- Tested in Android 14 and Android 12.

RMET-2723 Health & Fitness Plugin - Disconnect from google fit

---

CHANGELOG.md
src/android/build.gradle
src/android/com/outsystems/plugins/healthfitness/OSHealthFitness.kt

- This PR re-implements the `WriteProfileData` feature.
- It also includes a first draft version of the `getLastRecord` feature, which will be used for the `GetData` features (e.g. `GetFitnessData`).
References: https://outsystemsrd.atlassian.net/browse/RMET-3049
- Unit tests for the `WriteProfileData` feature were added to `src/test/kotlin/com/outsystems/plugins/healthfitness/WriteProfileDataTest.kt`.
- Tested in Android 14 Pixel 7, Android 13 Samsung A51, and Android 13 Pixel 3XL.

RMET-3049 OSHealthFitnessLib-Android - Migrate WriteProfileData feature

---

CHANGELOG.md
src/android/com/outsystems/plugins/healthfitness/OSHealthFitness.kt

- This PR re-implements the SetBackgroundJob feature.
References: https://outsystemsrd.atlassian.net/browse/RMET-3050
Tested on Android 14 Pixel 7 and Android 13 Samsung A51

RMET-3050 H&F Plugin - Migrate set background job

---

CHANGELOG.md
src/android/build.gradle
src/android/com/outsystems/plugins/healthfitness/OSHealthFitness.kt

- This PR re-implements the `UpdateBackgroundJob` feature.
References:
- https://outsystemsrd.atlassian.net/browse/RMET-3067
- Tested in Android 14 Pixel 7.

RMET-3067 H&F Plugin - Migrate updateBackgroundJob

---

src/android/build.gradle

- Updates the dependency to https://github.com/OutSystems/OSHealthFitnessLib-Android
References: https://outsystemsrd.atlassian.net/browse/RMET-3134
- Tested in Android 14 (Pixel 7), Android 12 (Pixel 3XL).

RMET-3134 H&F Plugin - Minor fix for background jobs feature

---

src/android/build.gradle

- Updates the dependency to https://github.com/OutSystems/OSHealthFitnessLib-Android
References: https://outsystemsrd.atlassian.net/browse/RMET-3134
- Tested in Android 14 (Pixel 7), Android 12 (Pixel 3XL).

RMET-3134 H&F Plugin - Apply fix background job

---

CHANGELOG.md
src/android/build.gradle

- Updates the version of the GSON library.
Version `2.8.9` fixes a vulnerability found in `2.8.8` that was reported by Snyk. More info [here](https://mvnrepository.com/artifact/com.google.code.gson/gson/2.8.8).
References: https://outsystemsrd.atlassian.net/browse/RMET-3134
Tested on Android 14 Pixel 7 device.
MABS 10 build: https://intranet.outsystems.net/MABS/BuildDetail.aspx?BuildId=aba1df2474274a3ba510b0ecf8ce94eaf8be9549

RMET-3134 H&F Plugin - Update GSON library version

---

src/android/build.gradle

- Updates dependency to https://github.com/OutSystems/OSHealthFitnessLib-Android
References: https://outsystemsrd.atlassian.net/browse/RMET-3051

RMET-3051 H&F Plugin - Prepare release of version 2.0.0

---

package.json
plugin.xml

References: https://outsystemsrd.atlassian.net/browse/RMET-3051

RMET-3051 H&F Plugin - Prepare to release version 2.0.0

---

CHANGELOG.md
hooks/androidCopyPrivacyUrlEnv.js

From MABS 10+, it's possible to customise the error message in order to appear on Service Studio/ODC Studio. This PR adds the necessary logic for this messages to appear.
[JIRA ISSUE](https://outsystemsrd.atlassian.net/browse/RMET-3388)
O11
ODC

RMET-3388 :: Hook :: Update Error Messages

---

CHANGELOG.md
src/android/build.gradle

- Updates the dependency to OSHealthFitnessLib-Android to `2.1.0`
References: https://outsystemsrd.atlassian.net/browse/RMET-3361
All unit tests passing.
Tested in Android 14 (Pixel 7), Android 13 (Samsung A51), and Android 12 (Pixel 3XL)
MABS build: https://intranet.outsystems.net/MABS/BuildDetail.aspx?BuildId=46de2f1caf41edfdc9cd6974c1ac2fc66be6bde1

RMET-3355 HealthFitness Plugin - Update OSHealthFitnessLib-Android to `2.1.0`

---

CHANGELOG.md
hooks/androidCopyPreferencesPermissions.js
package.json
plugin.xml

- This PR solves the conflicts between the `development` and `main` branches. As the `development` branch is protected, conflicts need to be solved via PR.
References: https://outsystemsrd.atlassian.net/browse/RMET-3367

RMET-3367 Health & Fitness Plugin - Solve conflicts between `development` and `main`

---

CHANGELOG.md
src/android/build.gradle
src/android/com/outsystems/plugins/healthfitness/OSHealthFitness.kt

- Updates the dependency to the Android native library to version `2.1.1` which fixes an incompatibility with the AppShield plugin.
References: https://outsystemsrd.atlassian.net/browse/RMET-3393
Tested in Android 14 (Pixel 7) with the following MABS 10 build: https://intranet.outsystems.net/MABS/BuildDetail.aspx?BuildId=63088c828ff05f9fa2efd8c87fb7033f0c710d83

RMET-3393 H&F Plugin - Fix incompatibility with AppShield plugin

---

package.json
plugin.xml
src/android/build.gradle

- Updates cordova plugin version to `2.1.1`
References: https://outsystemsrd.atlassian.net/browse/RMET-3475

RMET-3475 H&F Plugin - Prepare release of version `2.1.1`

---

CHANGELOG.md
hooks/androidCopyPreferencesPermissions.js
package.json
plugin.xml
src/android/build.gradle
src/android/com/outsystems/plugins/healthfitness/OSHealthFitness.kt

- This PRs adds the `requestReadDataBackgroundPermission` feature, to request the [READ_HEALTH_DATA_IN_BACKGROUND](https://developer.android.com/reference/android/health/connect/HealthPermissions#READ_HEALTH_DATA_IN_BACKGROUND) permission when setting a background job, for Android 15 devices.
- It updates the dependency to `OSHealthFitnessLib-Android` accordingly.
- This fixes an issue we had when processing a background job, where sometimes the `BackgroundJobManager.isDateToday` function would return false when it should return true, due to timezone differences.
- It also adds code to `hooks/androidCopyPreferencesPermissions.js` to include the new permission.
References:
- https://outsystemsrd.atlassian.net/browse/RMET-3574
- All unit tests passing.
- Tested in Android 14 (Pixel 7), …

RMET-3574 - Request `READ_HEALTH_DATA_IN_BACKGROUND` permission for Android 15

---

CHANGELOG.md
package.json
plugin.xml
src/android/build.gradle

- Prepares release of version `2.2.1`.
https://outsystemsrd.atlassian.net/browse/RMET-3819
- Manual testing was performed to validate the new feature.

RMET-3819 H&F - Prepare to release version `2.2.1`

---

CHANGELOG.md
package.json
plugin.xml
src/android/build.gradle
src/android/com/outsystems/plugins/healthfitness/OSHealthFitness.kt
src/android/com/outsystems/plugins/healthfitness/OSHealthFitnessWarning.kt
src/android/com/outsystems/plugins/healthfitness/TimeUnitSerializer.kt

- Merges `development` into `main`
https://outsystemsrd.atlassian.net/browse/RMET-3878
https://outsystemsrd.atlassian.net/browse/RMET-3831

RMET-3878 - Prepare to release version `2.3.0`

---

CHANGELOG.md
package.json
plugin.xml

Prepare `development` for `2.3.1` Release

---

CHANGELOG.md
package.json
plugin.xml

- Merges `development` into `main`.
References: https://outsystemsrd.atlassian.net/browse/RMET-4037

Prepare to release version `2.3.1`

---

CHANGELOG.md
hooks/androidCopyPreferencesPermissions.js
package.json
plugin.xml
src/android/build.gradle

- Merges `development` into `main`.
References: https://outsystemsrd.atlassian.net/browse/RMET-4179

RMET-4179 Prepare to release version `2.3.2`

---

CHANGELOG.md
package.json
plugin.xml

RMET-4278 prepare release 2.4.0

---

CHANGELOG.md
package.json
plugin.xml
src/android/build.gradle

- Updates dependency to `OSHealthFitnessLib-Android` to bring fix from https://github.com/OutSystems/OSHealthFitnessLib-Android/pull/65
- Prepares for the next release, setting the version of the plugin to `2.4.1`.
References: https://outsystemsrd.atlassian.net/browse/RMET-4353
Tested on Android 16 (Pixel 9 Pro XL) and Android 15 (Pixel 7) with MABS 11 and MABS 12 builds.
[MABS 11 build](https://intranet.outsystems.net/MABS_Lite/BuildDetail?id=8493dbcca3ccbb7efd83aa4d5d2368c923afae6d&stg=prd)
[MABS 12 build](https://eng-mobile.outsystems.dev/apps/packagehistory?id=bc5302d3-3f79-4ad7-80d2-0fca366ac26d&stageid=82798f0c-48de-4787-b0e1-dd3204ce2e6b)

RMET-4353 - Properly show status bar icons on Privacy Policy screen
